export const queryKeys = {
  groups: ["groups"] as const,
  groupsActive: ["groups", "active"] as const,
  group: (id: string) => ["groups", id] as const,
  yuvaks: ["yuvaks"] as const,
  yuvaksActive: ["yuvaks", "active"] as const,
  yuvaksByGroup: (groupId: string) => ["yuvaks", "group", groupId] as const,
  sabhas: ["sabhas"] as const,
  sabha: (id: string) => ["sabhas", id] as const,
  sabhaByDate: (date: string) => ["sabhas", "date", date] as const,
  attendance: (sabhaId: string) => ["attendance", sabhaId] as const,
  followups: ["followups"] as const,
  followupsByGroup: (groupId: string) => ["followups", "group", groupId] as const,
  followupsToday: (groupId: string) => ["followups", "today", groupId] as const,
  settings: ["settings"] as const,
  stats: {
    latest: ["stats", "latest"] as const,
    weekly: ["stats", "weekly"] as const,
    monthly: (y: number, m: number) => ["stats", "monthly", y, m] as const,
    yearly: (y: number) => ["stats", "yearly", y] as const,
    groupWise: (sabhaId: string) => ["stats", "group", sabhaId] as const,
    trend: (y: number) => ["stats", "trend", y] as const,
  },
};
