/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GroupFollowupsRouteImport } from './routes/group/followups'
import { Route as GroupDashboardRouteImport } from './routes/group/dashboard'
import { Route as GroupBirthdaysRouteImport } from './routes/group/birthdays'
import { Route as AdminYuvaksRouteImport } from './routes/admin/yuvaks'
import { Route as AdminStatisticsRouteImport } from './routes/admin/statistics'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminGroupsRouteImport } from './routes/admin/groups'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupFollowupsRoute = GroupFollowupsRouteImport.update({
  id: '/group/followups',
  path: '/group/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupDashboardRoute = GroupDashboardRouteImport.update({
  id: '/group/dashboard',
  path: '/group/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupBirthdaysRoute = GroupBirthdaysRouteImport.update({
  id: '/group/birthdays',
  path: '/group/birthdays',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYuvaksRoute = AdminYuvaksRouteImport.update({
  id: '/admin/yuvaks',
  path: '/admin/yuvaks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/admin/statistics',
  path: '/admin/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsRoute = AdminGroupsRouteImport.update({
  id: '/admin/groups',
  path: '/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/yuvaks': typeof AdminYuvaksRoute
  '/group/birthdays': typeof GroupBirthdaysRoute
  '/group/dashboard': typeof GroupDashboardRoute
  '/group/followups': typeof GroupFollowupsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/yuvaks': typeof AdminYuvaksRoute
  '/group/birthdays': typeof GroupBirthdaysRoute
  '/group/dashboard': typeof GroupDashboardRoute
  '/group/followups': typeof GroupFollowupsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/groups': typeof AdminGroupsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/yuvaks': typeof AdminYuvaksRoute
  '/group/birthdays': typeof GroupBirthdaysRoute
  '/group/dashboard': typeof GroupDashboardRoute
  '/group/followups': typeof GroupFollowupsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/attendance'
    | '/admin/dashboard'
    | '/admin/groups'
    | '/admin/settings'
    | '/admin/statistics'
    | '/admin/yuvaks'
    | '/group/birthdays'
    | '/group/dashboard'
    | '/group/followups'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/attendance'
    | '/admin/dashboard'
    | '/admin/groups'
    | '/admin/settings'
    | '/admin/statistics'
    | '/admin/yuvaks'
    | '/group/birthdays'
    | '/group/dashboard'
    | '/group/followups'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin/attendance'
    | '/admin/dashboard'
    | '/admin/groups'
    | '/admin/settings'
    | '/admin/statistics'
    | '/admin/yuvaks'
    | '/group/birthdays'
    | '/group/dashboard'
    | '/group/followups'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGroupsRoute: typeof AdminGroupsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminYuvaksRoute: typeof AdminYuvaksRoute
  GroupBirthdaysRoute: typeof GroupBirthdaysRoute
  GroupDashboardRoute: typeof GroupDashboardRoute
  GroupFollowupsRoute: typeof GroupFollowupsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/followups': {
      id: '/group/followups'
      path: '/group/followups'
      fullPath: '/group/followups'
      preLoaderRoute: typeof GroupFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/dashboard': {
      id: '/group/dashboard'
      path: '/group/dashboard'
      fullPath: '/group/dashboard'
      preLoaderRoute: typeof GroupDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/birthdays': {
      id: '/group/birthdays'
      path: '/group/birthdays'
      fullPath: '/group/birthdays'
      preLoaderRoute: typeof GroupBirthdaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/yuvaks': {
      id: '/admin/yuvaks'
      path: '/admin/yuvaks'
      fullPath: '/admin/yuvaks'
      preLoaderRoute: typeof AdminYuvaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/admin/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups': {
      id: '/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGroupsRoute: AdminGroupsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminYuvaksRoute: AdminYuvaksRoute,
  GroupBirthdaysRoute: GroupBirthdaysRoute,
  GroupDashboardRoute: GroupDashboardRoute,
  GroupFollowupsRoute: GroupFollowupsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
